#!/usr/bin/env bash

echo "== put objects in a bucket =="

# Check for the bucket name
if [ -z "$1" ]; then
    echo "There need to be a bucket name"
    exit 1
fi

BUCKET_NAME=$1

# List all the objects name of the specified bucket in one json
aws s3api list-objects-v2 \
--bucket $BUCKET_NAME \
--query Contents[].Key \
| jq -n '{Objects: [inputs | .[] | {Key: .}]}' > /tmp/delete_objects.json

# Delete the objects (we got from previous step) from the bucket
aws s3api delete-objects \
--bucket $BUCKET_NAME \
--delete file:///tmp/delete_objects.json