#!/usr/bin/env bash

echo "== list the objects of a bucket =="

# check for the bucket name
if [ -z "$1" ]; then
    echo "There need to be a bucket name here to be delted"
    exit 1
fi

aws s3api list-objects-v2 \
--bucket "$1"